basePath: /api/v1
definitions:
  main.album:
    properties:
      artist:
        type: string
      id:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /example/albums:
    get:
      consumes:
      - application/json
      description: getAlbum
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.album'
            type: array
      summary: getAlbums
      tags:
      - example
    post:
      consumes:
      - application/json
      description: postAlbums
      parameters:
      - description: Album
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/main.album'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.album'
      summary: postAlbums
      tags:
      - example
  /example/albums/{id}:
    get:
      consumes:
      - application/json
      description: getAlbumById
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: album
      summary: getAlbumById
      tags:
      - example
swagger: "2.0"
